### PR TITLE
Catch general exeception when git fails

### LINKED ISSUE #1291: Experiment tracking raising an issue in GitHub action
Hello there,

I hope that this finds you well. Thanks for the awesome work! Sorry to come with an issue. ☺️
Issue

## Description & context

I'm trying to set up kedro pipeline test as part of my CI/CD using GH action. Everything goes well until I receive a git related error

```
TypeError: HEAD is a detached symbolic reference as it points to 
'dc15ea87ce9d917bafb09d5d7bddb2aaf44f5989'
```

<details><summary>GH action config file</summary>

```yml
name: requirements-code-quality-tests
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  check-requirements-code-quality-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: "🏡 Checkout repository"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: "🐍 Install python"
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
        cache: "pip" # caching pip dependencies
    - name: "🧱 Check install cerrotorre dependencies"
      run: |
        pip install -r src/requirements.txt
        pip install -r src/requirements-dev.txt
        pip install -e src/
    - name: "🎨 Linting checks"
      run: |
        black --check src/
        isort --check src/
        pylint src/
    - name: "🧪 Check tests"
      run: pytest
    - name: "🏃 Check pipelines"
      run: |
        kedro run
        kedro run --pipeline evaluate_allotment

```

</details>

<details><summary>Error log</summary>

```raw
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /opt/hostedtoolcache/Python/3.8.16/x64/bin/kedro:8 in <module>               │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/kedro/fra │
│ mework/cli/cli.py:211 in main                                                │
│                                                                              │
│   208 │   """                                                                │
│   209 │   _init_plugins()                                                    │
│   210 │   cli_collection = KedroCLI(project_path=Path.cwd())                 │
│ ❱ 211 │   cli_collection()                                                   │
│   212                                                                        │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/click/cor │
│ e.py:1130 in __call__                                                        │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/kedro/fra │
│ mework/cli/cli.py:139 in main                                                │
│                                                                              │
│   136 │   │   )                                                              │
│   137 │   │                                                                  │
│   138 │   │   try:                                                           │
│ ❱ 139 │   │   │   super().main(                                              │
│   140 │   │   │   │   args=args,                                             │
│   141 │   │   │   │   prog_name=prog_name,                                   │
│   142 │   │   │   │   complete_var=complete_var,                             │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/click/cor │
│ e.py:1055 in main                                                            │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/click/cor │
│ e.py:1657 in invoke                                                          │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/click/cor │
│ e.py:1404 in invoke                                                          │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/click/cor │
│ e.py:760 in invoke                                                           │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/kedro/fra │
│ mework/cli/project.py:455 in run                                             │
│                                                                              │
│   452 │   with KedroSession.create(                                          │
│   453 │   │   env=env, conf_source=conf_source, extra_params=params          │
│   454 │   ) as session:                                                      │
│ ❱ 455 │   │   session.run(                                                   │
│   456 │   │   │   tags=tag,                                                  │
│   457 │   │   │   runner=runner(is_async=is_async),                          │
│   458 │   │   │   node_names=node_names,                                     │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/kedro/fra │
│ mework/session/session.py:303 in __exit__                                    │
│                                                                              │
│   300 │   def __exit__(self, exc_type, exc_value, tb_):                      │
│   301 │   │   if exc_type:                                                   │
│   302 │   │   │   self._log_exception(exc_type, exc_value, tb_)              │
│ ❱ 303 │   │   self.close()                                                   │
│   304 │                                                                      │
│   305 │   def run(  # pylint: disable=too-many-arguments,too-many-locals     │
│   306 │   │   self,                                                          │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/kedro/fra │
│ mework/session/session.py:295 in close                                       │
│                                                                              │
│   292 │   │   if `save_on_close` attribute is True.                          │
│   293 │   │   """                                                            │
│   294 │   │   if self.save_on_close:                                         │
│ ❱ 295 │   │   │   self._store.save()                                         │
│   296 │                                                                      │
│   297 │   def __enter__(self):                                               │
│   298 │   │   return self                                                    │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/kedro_viz │
│ /integrations/kedro/sqlite_store.py:67 in save                               │
│                                                                              │
│   64 │   │   engine, session_class = create_db_engine(self.location)         │
│   65 │   │   Base.metadata.create_all(bind=engine)                           │
│   66 │   │   database = next(get_db(session_class))                          │
│ ❱ 67 │   │   session_store_data = RunModel(id=self._session_id, blob=self.to │
│   68 │   │   database.add(session_store_data)                                │
│   69 │   │   database.commit()                                               │
│   70                                                                         │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/kedro_viz │
│ /integrations/kedro/sqlite_store.py:51 in to_json                            │
│                                                                              │
│   48 │   │   │   │   try:                                                    │
│   49 │   │   │   │   │   import git  # pylint: disable=import-outside-toplev │
│   50 │   │   │   │   │                                                       │
│ ❱ 51 │   │   │   │   │   branch = git.Repo(search_parent_directories=True).a │
│   52 │   │   │   │   │   value["branch"] = branch.name                       │
│   53 │   │   │   │   except ImportError as exc:  # pragma: no cover          │
│   54 │   │   │   │   │   logger.warning("%s:%s", exc.__class__.__name__, exc │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/git/repo/ │
│ base.py:896 in active_branch                                                 │
│                                                                              │
│    893 │   │   :raises TypeError: If HEAD is detached                        │
│    894 │   │   :return: Head to the active branch"""                         │
│    895 │   │   # reveal_type(self.head.reference)  # => Reference            │
│ ❱  896 │   │   return self.head.reference                                    │
│    897 │                                                                     │
│    898 │   def blame_incremental(self, rev: str | HEAD, file: str, **kwargs: │
│    899 │   │   """Iterator for blame information for the given file at the g │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/git/refs/ │
│ symbolic.py:309 in _get_reference                                            │
│                                                                              │
│   306 │   │   │   to a reference, but to a commit"""                         │
│   307 │   │   sha, target_ref_path = self._get_ref_info(self.repo, self.path │
│   308 │   │   if target_ref_path is None:                                    │
│ ❱ 309 │   │   │   raise TypeError("%s is a detached symbolic reference as it │
│   310 │   │   return self.from_path(self.repo, target_ref_path)              │
│   311 │                                                                      │
│   312 │   def set_reference(                                                 │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: HEAD is a detached symbolic reference as it points to 
'dc15ea87ce9d917bafb09d5d7bddb2aaf44f5989'
Error: Process completed with exit code 1.

```

</details>

## Expected Result

It should not fail, at least not because of that 😅

## Root cause and resolution approach

@AntonyMilneQB @deepyaman  have identified that the error comes form experiment tracking, specifically:

>Ultimately this is a bug with kedro-viz since the SQLiteStore shouldn’t fail due to a git error. [It’s already designed to work in the case that git isn’t installed](https://github.com/kedro-org/kedro-viz/blob/b9bd84ec3cde0afb32aedeed58dc7163eb57b1c1/package/kedro_viz/integrations/kedro/sqlite_store.py#L53) but we didn’t anticipate git throwing a TypeError. So we should change that except just to catch anything. 

Full discussion [here](https://kedro-org.slack.com/archives/C03RKP2LW64/p1679349236560359)

## Your Environment

kedro version: 0.18.6
python version: 3.8
OS: ubuntu/windows latest

## Checklist
- [x] Include labels so that we can categorise your issue

### PR DESCRIPTION
**Pull request by noklam**
## Description

Following https://github.com/kedro-org/kedro/issues/1826

Fixes #1291

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro-viz/pull/1380"></a>

### CODE REVIEW

**Comment by tynandebold** [comment]
How can I test this?

**Comment by noklam** [comment]
1. git checkout remotes/origin/main - Reproducing the same error when git is on a detach HEAD
 2. cd `demo-project`
 3. `kedro run` - Type Error
 4. git checkout remotes/originfix-git-exception
 5. `kedro run` - should run without issues

@tynandebold

**Review by tynandebold — APPROVED** [review]
Fantastic, looks good and works well.

**Comment by tynandebold** [comment]
Please add a line to the release notes for this as well!

**Pull request merged**
