### PR TITLE
Update `isRunningLocally` Function to Recognise Private IP Addresses for Consistent GUI Rendering

### PR DESCRIPTION
**Pull request by SajidAlamQB**
## Description

Related to: https://github.com/kedro-org/kedro-viz/issues/2198

This PR addresses an issue where Kedro-Viz does not display the full GUI when accessed via local private IP addresses (e.g., 192.168.x.x). We will update the `isRunningLocally` function to include private IP ranges defined in RFC 1918, to ensure consistent GUI rendering when accessing Kedro-Viz on local networks.

## Development notes

Regular expressions have been added to match the following private IP ranges:
```
10.0.0.0 – 10.255.255.255
172.16.0.0 – 172.31.255.255
192.168.0.0 – 192.168.255.255
```

## QA Notes

Local Access via localhost:

**Run Kedro-Viz:**

- `kedro viz run --host=0.0.0.0 --port=1008`
- Open http://localhost:1008 or http://127.0.0.1:1008 on your machine.
- Expected: All local-only features (like the Experiment Tracking tab) should be visible and functional.

**Local Access via IP:**

- Find your machine’s local IP (e.g., 192.168.1.40).
- On the same machine, access http://192.168.1.40:1008.
- Expected: All local-only features appear, just as they do with localhost.

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by Huongg** [comment]
hey thank @SajidAlamQB just a quick reminder to add this in the release note, and also can you also put a few notes in the QA steps please, eg: is there anything we should run locally to test this specifically?

**Comment by SajidAlamQB** [comment]
> hey thanks @SajidAlamQB just a quick reminder to add this in the release note, and also can you also put a few notes in the QA steps please, eg: is there anything we should run locally to test this specifically?

I've added it in the description:

Run Kedro-Viz:

- `kedro viz run --host=0.0.0.0 --port=1008`
- Open http://localhost:1008/ or http://127.0.0.1:1008/ on your machine.
- Expected: All features (like the Experiment Tracking tab) should be visible and functional.

Local Access via IP:

- Find your machine’s local IP (e.g., 192.168.1.40).
- On the same machine, access http://192.168.1.40:1008/.
- Expected: All features appear, just as they do with localhost.

**Review by jitu5 — APPROVED** [review]
Thanks @SajidAlamQB

**Review by Huongg — APPROVED** [review]
thank you @SajidAlamQB

**Pull request merged**
