### PR TITLE
Update the styling on the Viz nudge feature

### LINKED ISSUE #924: Missing correct styles on Viz update nudge
## Description

- Update nudge doesn’t show correct hover states when interacting with links.
- Some fontsizes don’t match design.
- Link accent colours don’t match design (“view release notes”) 

Screen Recording 2022-06-17 at 10 16 1

image

## Acceptance criteria

- All font sizes, accent colours and link styles should match the reference links design.

Reference links: 

https://zpl.io/aRw5WoE
https://zpl.io/awdRWn1

## Checklist
- [x] Include labels so that we can categorise your issue

### PR DESCRIPTION
**Pull request by tynandebold**
Signed-off-by: Tynan DeBold <thdebold@gmail.com>

## Description

Fixes #924.

## Development notes

I fixed the styles to make sure they match what's shown in Zeplin.

This also fixes a small issue with the font sizes on the toggles in the settings panel:

image

## QA notes

Look at the Gitpod link and check the styles against the design. Note that I'm hardcoding the versions nudge to show up. I'll remove that code before merging.

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [x] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro-viz/pull/933"></a>

### CODE REVIEW

**Comment by GabrielComymQB** [comment]
Hi, I guess it all looks cool to me apart from the accent colour on the external link that looks very muted.

Screenshot 2022-06-20 at 17 17 53

**Comment by tynandebold** [comment]
> Hi, I guess it all looks cool to me apart from the accent colour on the external link that looks very muted.
> 
> Screenshot 2022-06-20 at 17 17 53

Ah yes, great catch. I've fixed it now.

**Comment by GabrielComymQB** [comment]
> > Hi, I guess it all looks cool to me apart from the accent colour on the external link that looks very muted.
> > Screenshot 2022-06-20 at 17 17 53
> 
> Ah yes, great catch. I've fixed it now.

Looks great! on the dark theme - as always
But here again, we have a question about the light version which doesn't pass the right contrast ratio.

If we can, I suggest making the link #076E9C on the light version. 

Screenshot 2022-06-20 at 18 45 12

If you think this is too much/messy for now, leave it and we'll treat the light version properly in one go after the coming up rebranding exercise.

**Comment by tynandebold** [comment]
> 

True. I think it's ok to update this now, so I've done that it.

**Review by cvetankanechevska — APPROVED** [review]
Looks great to me!

**Review by GabrielComymQB — APPROVED** [review]

**Pull request merged**
