### PR TITLE
Reload the page resets back the default pipeline

### PR DESCRIPTION
**Pull request by SajidAlamQB**
## Description

Related to: https://github.com/kedro-org/kedro-viz/issues/1997

When you're in any other pipeline view rather the default pipeline, if you load the URL again, it will reset to the default page.

## Development notes

- Introduced the `modularPipelineTree` logic to ensure that only the children of a modular pipeline are expanded.

- Added a check to avoid overwriting the active pipeline if one is already set.

- Removed the `urlParams` from `preparePipelineState` in the `getInitialState` method, as they were causing unexpected overwrites.

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by SajidAlamQB** [comment]
One issue I noticed was when you're in any other pipeline view except the default and you click a node when the page refreshes the node is not highlighted anymore and the metadata panel doesn't open. In the default view reloading with a node selected keeps it highlighted and opens metadata panel.

**Review by rashidakanchwala — APPROVED** [review]
works for me. thanks

**Comment by Huongg** [comment]
hey @SajidAlamQB I think the pipeline bug is fixed now but as you said there's other bug about the selected node is not highlighted and metadata panel is not opened. And even in the default pipeline, the node is not highlighted even the meta data panel opens 🤔 

Screenshot 2024-08-19 at 17 00 18

**Comment by SajidAlamQB** [comment]
> hey @SajidAlamQB I think the pipeline bug is fixed now but as you said there's other bug about the selected node is not highlighted and metadata panel is not opened. And even in the default pipeline, the node is not highlighted even the meta data panel opens 🤔

I'm not able to see the bug with the default pipeline, but it does exist with the other pipeline views. I'm not to sure the best fix for this do you have any ideas?

**Comment by Huongg** [comment]
> > hey @SajidAlamQB I think the pipeline bug is fixed now but as you said there's other bug about the selected node is not highlighted and metadata panel is not opened. And even in the default pipeline, the node is not highlighted even the meta data panel opens 🤔
> 
> I'm not able to see the bug with the default pipeline, but it does exist with the other pipeline views. I'm not too sure what the best fix for this is, do you have any ideas?

hey I can still see the issue from my side. I think it might be related to your previous issue. Have you looked at `redirectToSelectedNode` in `FlowchartWrapper`? Perhaps the issue started there. This is where we get the params from the URL and load the node if nodeID existed etc. Perhaps something went missing there? 🤔 happy to jump on the call to do it together if it helps

**Comment by SajidAlamQB** [comment]
> hey @SajidAlamQB I can still see the issue from my side. I think it might be related to your previous issue. Have you looked at `redirectToSelectedNode` in `FlowchartWrapper`? Perhaps the issue started there. 

@Huongg I will make this into a separate issue, its not related to the changes for this PR.

**Comment by SajidAlamQB** [comment]
This PR also fixes two unrelated bugs:

1. **Flowchart View Splitting into Two Trees When `Expand Modular Pipelines` is Enabled**:
When the `Expand Modular Pipelines` button was enabled with `expandAllPipelines=true` in the query string, selecting a node and refreshing the page caused the flowchart view to break, splitting it into two separate trees (see the screenshot below):

image

I believe the cause was that modular pipelines was being expanded unnecessarily, regardless of the `expandAllPipelines` flag. I added an additional condition `!expandAllPipelines` to make sure that modular pipelines only expand when the "Expand All Pipelines" option is disabled:
```
if (hasModularPipeline && !isParameterType && !expandAllPipelines) {
     onToggleModularPipelineExpanded(modularPipeline);
}
```

2. **Node Not Highlighted After Page Refresh in Non-Default Pipeline views**:
The second bug happened when a node was not highlighted after refreshing the page in non-default pipeline views. This happened because the condition checking graph initialisation `graphRef.current === null` didn’t account for page refreshes. To fix this, I used the `PerformanceNavigationTiming` API to detect page reloads and added it as a check in the condition:
```
const navigationEntries = performance.getEntriesByType('navigation');
const isPageRefreshed = navigationEntries.length && navigationEntries[0].type === 'reload';

if (
   (graphRef.current === null || usedNavigationBtn || isInvalidUrl || isPageRefreshed) &&
   !isGraphEmpty
) {
```

**Review by Huongg — APPROVED** [review]
it's working from my side, thanks @SajidAlamQB for the changes 👍

**Comment by SajidAlamQB** [comment]
> @SajidAlamQB have you tested with this scenario #1879 ?

I've tested it and it now opens on this page:

image

**Review by jitu5 — APPROVED** [review]
Thanks @SajidAlamQB and @rashidakanchwala.

**Pull request merged**
