### PR TITLE
Release/6.2.0

### PR DESCRIPTION
**Pull request by Huongg**
## Description

Major release for the collaborative experiment tracking

## What changes
- Update the version to 6.2.0
- Update the content for the viz version panel

Screenshot 2023-05-25 at 17 12 26

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro-viz/pull/1368"></a>

### CODE REVIEW

**Review by rashidakanchwala — APPROVED** [review]
LGTM :)

**Comment by tynandebold** [comment]
I don't think is good to go. Have you checked the Gitpod link? There aren't any experiments on the experiment tracking page. @rashidakanchwala I'm guessing this is related to your collaborative experiment tracking PR. Can you please investigate?

**Comment by Huongg** [comment]
ah yeah good point thanks @tynandebold. I only noticed it now when checking gitpod. I guess it's because the gitpod doesn't have access to the storage, or doesn't know where to get the data from. I assume it will be the same issue for the demo site

**Comment by tynandebold** [comment]
I see the same thing locally though, so I don't think it's Gitpod related. Maybe the session store file was overwritten when Rashida was doing her PR?

**Review by tynandebold — APPROVED** [review]
LGTM!

**Review by NeroOkwa — APPROVED** [review]
Looks really good!

**Pull request merged**
