### PR TITLE
Fix broken URL when active pipeline name changes on initial load

### PR DESCRIPTION
**Pull request by ravi-kumar-pilla**
## Description

Resolves [#1879](https://github.com/kedro-org/kedro-viz/issues/1879)

pid_fix

## Development notes

* Remove params check to update activePipeline

## QA notes

* Run `kedro viz run` -> Change the pipeline id in pipeline_registry of your kedro project -> Run `kedro viz run`. The URL should point to the new pipeline id.
* All tests should pass

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [x] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by jitu5 — APPROVED** [review]
LGTM!

**Review by Huongg — APPROVED** [review]
LGTM too, thanks @ravi-kumar-pilla

**Comment by ravi-kumar-pilla** [comment]
Hi @rashidakanchwala ,

Could you please remove the CircleCI integration for this repo ? Thank you

image

**Comment by jitu5** [comment]
@ravi-kumar-pilla to remove CircleCI Pipeline check you need to sync with main as you branch will have .circleCI config

**Comment by ravi-kumar-pilla** [comment]
> @ravi-kumar-pilla to remove CircleCI Pipeline check you need to sync with main as you branch will have .circleCI config

I already did - https://github.com/kedro-org/kedro-viz/commit/c26b16e7b95ebf82d73e1e0d2de7fc8d76c2dcea

**Comment by jitu5** [comment]
> > @ravi-kumar-pilla to remove CircleCI Pipeline check you need to sync with main as you branch will have .circleCI config
> 
> I already did - [c26b16e](https://github.com/kedro-org/kedro-viz/commit/c26b16e7b95ebf82d73e1e0d2de7fc8d76c2dcea)

@ravi-kumar-pilla Rashida recently did it and after that I sync with main and that check is gone. https://github.com/kedro-org/kedro-viz/pull/1894
Please push something to this branch.

**Comment by rashidakanchwala** [comment]
i enabled it now, maybe you need to do another push to re-run the workflows.

**Pull request merged**
