### PR TITLE
Release v9.2.0

### PR DESCRIPTION
**Pull request by SajidAlamQB**
## Description

# Release 9.2.0

## Major features and improvements

- Enable/disable preview for all the datasets when publishing Kedro-Viz from CLI. (#1894)
- Enable/disable preview for all the datasets when publishing Kedro-Viz from UI. (#1895)
- Display published URLs. (#1907)
- Conditionally move session store and stats file to .viz directory. (#1915)
- Introduce `metadataPanel` in `display` prop in Kedro-Viz react component. (#1965)
- Refactor namespace pipelines. (#1897)
- Expose the internal Redux state through `options` prop while using Kedro-Viz as a React component. (#1969)
- Enhance documentation for the Kedro-Viz standalone React component. (#1954)
- Add Datasets preview toggle in the settings panel. (#1977)

## Bug fixes and other changes

- Relax `packaging` pin in requirements. (#1947)
- Add favicon to kedro-viz documentation. (#1959)
- Add "-p" flag to kedro-viz to match kedro run. (#1960)
- Fix bug related to nested namespace pipelines. (#1897)
- Migrate from `toposort` to `graphlib`. (#1942)
- Fix packaging. (#1766)
- Adjust requirements file and dependabot versioning strategy. (#1978)
- Refactor CommandCopier component. (#1998)
- Set `isPrettyName` toggle to False by Default. (#1958)
- Add `-p` argument option for `kedro viz` to align with kedro pipeline options. (#1961)
- Replace `data-heap-event` with standardised `data-test` for Cypress and Telemetry. (#1995)

## Community contributions

Many thanks to the following Kedroids for contributing PR to this release:
* [Vlad Cozma](https://github.com/VladCozma)

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [x] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by ravi-kumar-pilla** [comment]
Hi @SajidAlamQB , Thank you for the release PR.

**Some PRs worth mentioning in the Release -**

1. Set isPrettyName to False by Default #1958. - (User facing change, might be worth mentioning)
2. Added "-p" cli option to match kedro pipeline options #1961. - (Worth mentioning as community contribution)
3. Refactor: Replace data-heap-event with standardized data-test for Cypress and Telemetry #1995. - (For our tracking)

I hope there will be some update to the reminder content. Thank you

**Review by astrojuanlu — APPROVED** [review]
ship-it

**Comment by Huongg** [comment]
hey @SajidAlamQB I'm testing it locally now but just a reminder to update the feature-hint panel when the release

**Review by jitu5 — APPROVED** [review]
Great work team! 🎉

**Comment by ravi-kumar-pilla** [comment]
Hi Team,

When I refresh viz after selecting a different pipeline, it resets back to default. I would like if someone can test this behavior (pid resetting to default on refresh) and confirm. I think this is a bug. Thank you

cc: @jitu5 

pipeline_resetting_to_default

**Comment by jitu5** [comment]
> Hi Team,
> 
> When I refresh viz after selecting a different pipeline, it resets back to default. I would like if someone can test this behavior (pid resetting to default on refresh) and confirm. I think this is a bug (v9.0.0 works fine. The issue started in v9.1.0). Thank you
> 
> cc: @jitu5
> 
> pipeline_resetting_to_default [ pipeline_resetting_to_default ](https://private-user-images.githubusercontent.com/87735534/352549208-78af5501-01a3-4ca8-81f0-285020906b31.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDEzNzcsIm5iZiI6MTcyMjAwMTA3NywicGF0aCI6Ii84NzczNTUzNC8zNTI1NDkyMDgtNzhhZjU1MDEtMDFhMy00Y2E4LTgxZjAtMjg1MDIwOTA2YjMxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEzMzc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZTg2ZTJjYmM1NWU3ZjM0NDMwY2RhMTYyMWZlYTJjMjVmZjI2YzYyZTg0YjhlNTFkODAwYjhhZmRiNWQyZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kC_cYBEF4gPOEn6Vz2KGDWmBjzvsEesxZK0VvCKCncM) [ ](https://private-user-images.githubusercontent.com/87735534/352549208-78af5501-01a3-4ca8-81f0-285020906b31.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDEzNzcsIm5iZiI6MTcyMjAwMTA3NywicGF0aCI6Ii84NzczNTUzNC8zNTI1NDkyMDgtNzhhZjU1MDEtMDFhMy00Y2E4LTgxZjAtMjg1MDIwOTA2YjMxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEzMzc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZTg2ZTJjYmM1NWU3ZjM0NDMwY2RhMTYyMWZlYTJjMjVmZjI2YzYyZTg0YjhlNTFkODAwYjhhZmRiNWQyZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kC_cYBEF4gPOEn6Vz2KGDWmBjzvsEesxZK0VvCKCncM)


@ravi-kumar-pilla its already on demo site, and Huong already created bug ticket on this https://github.com/kedro-org/kedro-viz/issues/1997

**Review by ravi-kumar-pilla — APPROVED** [review]
LGTM. Thank you @SajidAlamQB

**Comment by Huongg** [comment]
i tested the branch locally and all the UI changes are working as expect. Great job team, looking forward to releasing to our users ❤️

**Review by rashidakanchwala — COMMENTED** [review]
Screenshot 2024-07-26 at 20 53 00

- If we can do so, could we add some formatting to the text to make certain key words bold
'enable' , 'disable', .viz etc. 
- Also, could we add link to the documentation to show how they can disable in CLI and in UI 
- The session store **(a SQLite database)** and the stats file are now conditionally

**Review by stephkaiser — APPROVED** [review]

**Review by rashidakanchwala — APPROVED** [review]
LGTM. thanks @SajidAlamQB

**Pull request merged**
