### PR TITLE
Improve Kedro-viz experience on notebooks

### PR DESCRIPTION
**Pull request by SajidAlamQB**
## Description
When using the `%run_viz` command for `kedro-viz` in Jupyter notebooks, it should open Kedro-viz in a new browser tab.

## Development notes
image

When clicking `Open Kedro-Viz` a new tab is opened:

image

## QA notes
Added one new unit tests that checks the target attribute is set `to _blank`, and the link text is `Open Kedro-Viz`.

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [x] Added tests to cover my changes

### CODE REVIEW

**Comment by astrojuanlu** [comment]
I notice in the screenshot that you're using an old version of Jupyter notebook, @SajidAlamQB could you try with `notebook>=7.0`? It was completely refactored and it's now based on JupyterLab internally.

**Comment by SajidAlamQB** [comment]
> I notice in the screenshot that you're using an old version of Jupyter notebook, @SajidAlamQB could you try with `notebook>=7.0`? It was completely refactored and it's now based on JupyterLab internally.

Here is what it looks like with `notebook>=7.0`:

image

image

**Review by rashidakanchwala — APPROVED** [review]
Look's great. Thanks Sajid! :)

**Review by merelcht — APPROVED** [review]
LGTM 👍 Should this change be included in the release notes?

**Pull request merged**
