### PR TITLE
Migrate to React 18

### PR DESCRIPTION
**Pull request by MehdiNV**
## Description
Migration of kedro-viz from React 17 to React 18

## Breakdown of changes
**Versionings:**
- Update React from 17 to 18
- Update Redux from 7 to 8
- Update adapter from 17 to 18 (to handle React 18)
- Updating several other dependencies to higher versioning (Jest, Webpack et al)
- Adjusting existing list of dependencies (e.g. removing enzyme)

**Code changes**
- Adjusting existing code to be compatible w/ React 18 (particularly its batching rules)
- Adapting Kedro-Viz to act as a component (for +compatibility)

## Development notes

Upgrading React 18 required updates to other dependencies (e.g. Redux, Adapter, removal and addition of some dependencies), as well as changes to existing codebase (as otherwise React would default back to 17 per its own API). Hence why the scope of this PR covers multiple dependency changes and large changes to codebase solely for this migration.

## QA notes

Combination of existing E2E testing (via Cypress), and manual QA to cover areas that existing tests haven't covered yet

### CODE REVIEW

**Review by tynandebold — COMMENTED** [review]
Nice work!

One quick question: we were often getting dependabot alerts to upgrade `react-scripts` from v4 to v5. Wonder if it's trivial to do that upgrade now in this PR?

**Comment by jitu5** [comment]
@tynandebold Sure let me explore `react-scripts` from v4 to v5 upgrade in this PR.

**Review by ravi-kumar-pilla — APPROVED** [review]
Looks good to me and works well locally ! Awesome job !!

**Comment by jitu5** [comment]
@tynandebold I tried upgrading `react-scripts` from v4 to v5. This internally upgraded `Webpack` from v4 to v5, and since `Webpack` v5 includes many breaking changes, it required updating several dependencies in the app. I've managed to upgrade most of the dependencies, but it seems that `workerize-loader` doesn't work well with `Webpack` v5. Therefore, for now, we've decided not to include it in this PR and will address it later.

**Review by rashidakanchwala — APPROVED** [review]
LGTM!

**Pull request merged**
