### PR TITLE
Release v5.3.0

### PR DESCRIPTION
**Pull request by tynandebold**
## Description

Release v5.3.0.

It's a minor-version release because we're adding some new functionality as well as some fixes.

> **Note**
> We'll wait until Kedro v0.18.5 is released before merging this.

Here's what's going in:

#### Major features and improvements

- Enable the display of json objects with `react-json-viewer` in experiment tracking. (#1236)
- Always show pretty and original node names in the metadata panel. (#1254)
- Display delta value for metrics when comparing runs in experiment tracking. (#1257)

#### Bug fixes and other changes

- Fix run command for task nodes on metadata panel. (#1245)
- Fix URL query params with expand all modular pipelines toggle. (#1256)

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by yetudada — APPROVED** [review]
Do we want to mention the docs changes here too? ❤️ But I'm so excited!

**Comment by tynandebold** [comment]
Good point! I think that would go in the framework repo though, since that's where the content lives and the changes are made.

**Review by AntonyMilneQB — APPROVED** [review]
:shipit: but why do we need to wait for kedro 0.18.5?

**Review by rashidakanchwala — APPROVED** [review]
Look's good. thanks @tynandebold  

Did a QA found two other minor issues (not related) that can be fixed in the next release.

**Comment by tynandebold** [comment]
@AntonyMilneQB there are some documentation changes that need to hit `stable` on readthedocs first.

**Pull request merged**
