### PR TITLE
Replace toposort with graphlib

### PR DESCRIPTION
**Pull request by SajidAlamQB**
## Description

Related to: [#1820](https://github.com/kedro-org/kedro-viz/issues/1820)

This ticket aims at dropping toposort dependency in favor of built-in graphlib if possible.

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by rashidakanchwala — APPROVED** [review]
LGTM, and the tests are all passing.

So Toposort performs several tasks under the hood, such as determining the layer and parent layer relationships. But, with graphlib, we must explicitly ensure that we don't add a layer as its own parent. Interesting.

**Comment by SajidAlamQB** [comment]
> Layers **feature** and **model_input** are shifted. Even the DAG has `Feature Importance Output` dataset after `Model Input Table`. Can you please test it on your side. Thank you

Hey @ravi-kumar-pilla, this should be fixed now let me know if its all fine.

**Comment by ravi-kumar-pilla** [comment]
> Hey @ravi-kumar-pilla, this should be fixed now let me know if its all fine.

Hi @SajidAlamQB , I tested it now and the order looks good. Thank you for that. May I know why was the static order different or why - `return sorted(sorted_layers, key=lambda layer: (sorted_layers.index(layer), layer))` was needed.

**Comment by SajidAlamQB** [comment]
> > Hey @ravi-kumar-pilla, this should be fixed now let me know if its all fine.
> 
> Hi @SajidAlamQB , I tested it now and the order looks good. Thank you for that. May I know why was the static order different or why - `return sorted(sorted_layers, key=lambda layer: (sorted_layers.index(layer), layer))` was needed.

The order of layers by the `TopologicalSorter` was decided by their insertion order. Since the insertion order was not stable it led to unexpected ordering in the output. So adding that final sort helped maintain the original input order. I will add some comments here for future reference as well.

**Review by astrojuanlu — APPROVED** [review]
LGTM! 👏🏼

**Pull request merged**
