### PR TITLE
Chore/change runsList route name to experiment-tracking

### LINKED ISSUE #819: [KED-3079] [FE] Change runsList route name to something more appropriate
(transfer from  Jira, created by @tynandebold)

Having [runsList](https://demo.kedro.org/runsList) as the URL route for experiment tracking seems like a poor choice. Let's change it to `/experiment-tracking` or something along those lines.

Kedro core reference: https://kedro.readthedocs.io/en/stable/08_logging/02_experiment_tracking.html

### PR DESCRIPTION
**Pull request by tynandebold**
## Description

Resolves #819.

## Development notes

This was just a switch of a couple of strings.

## QA notes

Checkout the branch and check the experiment-tracking page.

cc @NeroOkwa take a look at Joel's comment [here](https://github.com/kedro-org/kedro-viz/issues/819#issuecomment-1095272017).

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [x] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro-viz/pull/820"></a>

### CODE REVIEW

**Review by limdauto — APPROVED** [review]
Thanks. It's definitely an improvement. My only minor feedback is `experiment-tracking` is a bit too long, although it could help raise product awareness.

**Comment by tynandebold** [comment]
> Thanks. It's definitely an improvement. My only minor feedback is `experiment-tracking` is a bit too long, although it could help raise product awareness.

Too long based on...? Would love other suggestions. I'm struggling to come up with something better atm.

**Comment by limdauto** [comment]
@tynandebold  I was thinking it would be too long to manually type but not clear how many people would do that. Maybe `/experiments`? I was going to suggest that but realise maybe it will confuse users with this being an experimental feature.

**Comment by yetudada** [comment]
I'm happy with it being `experiment-tracking`; `experiments` is slightly confusing.

**Review by rashidakanchwala — APPROVED** [review]
LGTM!

**Pull request merged**
