### PR TITLE
[Experiment] Show/Hide Memory Datasets on the flowchart

### PR DESCRIPTION
**Pull request by rashidakanchwala**
## Description

Related to #1706. should we provide users with the option to display or hide Memory Datasets in the view? This feature can be particularly helpful for larger and more complex pipelines. This PR offers an experimental toggle to show/hide Memory Datasets, functioning similarly to the show/hide dataset.

This is currently not under experiment flag. 

## Development notes

MemoryDatasetsHidden

## Checklist

- [ ] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by inigohidalgo** [comment]
What happens to nodes which only have memory datasets as inputs and outputs? just a line connecting them to the last dataset which isn't memory?

**Comment by ravi-kumar-pilla** [comment]
This is a great feature to show/hide dataset types reducing the size of the flowchart. I have concerns over the placement of Memory Datasets under Element Types. It would be nice to have a hierarchy where these fall under Datasets.

**Comment by merelcht** [comment]
Would this just be for `MemoryDataset` or any non persistent datasets?

**Comment by datajoely** [comment]
For the purposes of this experiment I think `MemoryDataSet` gets us 80% of the way. There has already been questions in this PR whether we can visually differentiate datasets of different types.

**Comment by DebanjanBanerjeeQB** [comment]
Unpopular opinion and this is already fantastic work but 2 thoughts.

I dont see why this feature will be super impactful. Would love to hear your thoughts. 

- i would treat `memorydatasets` as any other dataset in the logical flow , it should have any different treatment / handling
- i wouldn't hide it ever , i wouldn`t hide any dataset ever because that risks an incorrect data lineage or risk of discounting a dataset while demoing or explaining the pipelines to anyone. 

If the goal is to signal users that these datasets use cache or inmemory storage and not persisted storage , i would create a tooltip or a separate action to explain datasets (all datasets) . Something that on hovering gives basic information about the datasets like 

- Dataset Type
- Some stats (Optional)
- Path 

WDYT ?

**Comment by rashidakanchwala** [comment]
> What happens to nodes which only have memory datasets as inputs and outputs? just a line connecting them to the last dataset which isn't memory?

Hey, there would be line connecting the two task/function nodes. Below is an example of Memory Dataset shown and then hidden. 


Screenshot 2024-01-17 at 21 56 03
Screenshot 2024-01-17 at 21 57 11

**Comment by datajoely** [comment]
I think it might be nice to have more powerful, persistent exclusion functionality - but I agree that #1706 is better. 

Again pointing to dbt, they have an ability for the user to provide [custom colors](https://docs.getdbt.com/reference/resource-configs/docs#custom-node-colors) - a long time ago I pitched https://github.com/kedro-org/kedro-viz/issues/480 which was turned into https://github.com/kedro-org/kedro-viz/issues/1148 but hasn't been prioritised.

**Comment by DebanjanBanerjeeQB** [comment]
One more solution could be 

- Identify all the different types of datasets in the pipeline
- put them as a list and checkboxes
- whatever user needs can select / deselect from the view to highlight. 

That covers the memory dataset but also makes the approach more open to other dataset types.

**Comment by DebanjanBanerjeeQB** [comment]
Screenshot 2024-01-18 at 10 30 28

Something like this ?

**Comment by rashidakanchwala** [comment]
Closing this experiment PR for now -- allowing users to differentiating datasets on kedro-viz seems like a good idea. We are going to try and do #1148 first and see how that picks up with users.

**Pull request closed without merging**
