### PR TITLE
Deferred dependencies import into run_server

### PR DESCRIPTION
**Pull request by jitu5**
## Description

Resolves https://github.com/kedro-org/vscode-kedro/issues/72

https://github.com/kedro-org/kedro-viz/pull/2049 To get current Kedro project JSON data required by Kedro-Viz React component when running inside VSCode, We introduce `get_kedro_project_json_data` function in `responses.py `which returns current Kedro project JSON data. But before `get_kedro_project_json_data`  we need to load and populate data with `load_and_populate_data` method from `server.py` 

To avoid ImportError when importing `load_and_populate_data` from `server.py` in VSCode extension, Deferred dependencies like `fsspec`, `uvicorn`, `multiprocessing` and `watchgod` inside `Run_server`.

## Development notes

- Moved dependencies like `fsspec`, `uvicorn`, `multiprocessing` and `watchgod` inside `Run_server`.

## Checklist

- [X] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by noklam** [comment]
Is it possible to extract load and populate data instead? That doesn't sound like something belong to server.py to start with.

**Comment by jitu5** [comment]
> Is it possible to extract load and populate data instead? That doesn't sound like something belong to server.py to start with.

@noklam I started with that moved `populate_data` and `load_and_populate_data` to separate file `load_data.py` but @ravi-kumar-pilla suggested to use deferred dependencies approach similar to what we did here https://github.com/kedro-org/kedro-viz/pull/1920#event-14070771509

**Comment by ravi-kumar-pilla** [comment]
> > Is it possible to extract load and populate data instead? That doesn't sound like something belong to server.py to start with.

I think we can definitely move load data to a different file.

> @noklam I started with that moved `populate_data` and `load_and_populate_data` to separate file `load_data.py` but @ravi-kumar-pilla suggested to use deferred dependencies approach similar to what we did here [#1920 (comment)](https://github.com/kedro-org/kedro-viz/pull/1920#event-14070771509)

I might be missing some context here. I was in an impression that you created the file just to resolve the import errors. So suggested to move the imports within the function. We can do the refactoring as well.

**Comment by noklam** [comment]
>  I started with that moved populate_data and load_and_populate_data to separate file load_data.p

What would that look likes?

> @ravi-kumar-pilla suggested to use deferred dependencies approach similar to what we did here https://github.com/kedro-org/kedro-viz/pull/1920#event-14070771509

What's the reason for that? I am fine with the deferred approach but I think `load_data`, `load_and_populate_data` does not belongs to `server.py`. There are some rooms for de-coupling as well, as https://github.com/kedro-org/kedro-viz/blob/084d3e79612a99751c7b665e1fdb97b32d8f1735/package/kedro_viz/integrations/kedro/data_loader.py#L72, `include_hook` also doesn't affect the data at all. This bundle the data for flowchart and the application itself (i.e. dataset preview).

**Comment by jitu5** [comment]
> > > Is it possible to extract load and populate data instead? That doesn't sound like something belong to server.py to start with.
> 
> I think we can definitely move load data to a different file.
> 
> > @noklam I started with that moved `populate_data` and `load_and_populate_data` to separate file `load_data.py` but @ravi-kumar-pilla suggested to use deferred dependencies approach similar to what we did here [#1920 (comment)](https://github.com/kedro-org/kedro-viz/pull/1920#event-14070771509)
> 
> I might be missing some context here. I was in an impression that you created the file just to resolve the import errors. So suggested to move the imports within the function. We can do the refactoring as well.

Yes, I created the file just to resolve the import errors.

**Comment by jitu5** [comment]
> > I started with that moved populate_data and load_and_populate_data to separate file load_data.p
> 
> What would that look likes?

https://github.com/kedro-org/kedro-viz/pull/2060/commits/80d35b6865b2c030e34a428a1176befd08439509#diff-94c1c8a57783f10e120cb066fe8582a44e256679802723204e8b5b4d7fd8d6b4

**Comment by ravi-kumar-pilla** [comment]
> What's the reason for that? I am fine with the deferred approach but I think `load_data`, `load_and_populate_data` does not belongs to `server.py`. There are some rooms for de-coupling as well, as
> 
> https://github.com/kedro-org/kedro-viz/blob/084d3e79612a99751c7b665e1fdb97b32d8f1735/package/kedro_viz/integrations/kedro/data_loader.py#L72


I agree with you, there is definitely a room to refactor the server.py file and keep it only to run server. We do have a refactoring ticket here - https://github.com/kedro-org/kedro-viz/issues/2061 and we can consider some refactor of server.py in this.

> , `include_hook` also doesn't affect the data at all. This bundle the data for flowchart and the application itself (i.e. dataset preview).

include_hook is used to create a NullPluginManager when we do KedroSession._hook_manager. Again, we can decouple and create more pure python functions. 

We can go ahead with deferred imports for now if it makes sense and you can add suggestion to  https://github.com/kedro-org/kedro-viz/issues/2061 or we can create a different ticket to refactor these as it might involve file changes in tests as well and other references and keep PRs small. Let me know what do you think

Thank you

**Comment by noklam** [comment]
Perfect, since there is a refactor ticket going on let's do the proper refactoring there. For now keeping this import deferred is sufficient.

**Review by noklam — APPROVED** [review]
As discussed in the comment, let's do this as deferred import and address the refactoring in a separate PR.

**Review by rashidakanchwala — APPROVED** [review]

**Pull request merged**
