### PR TITLE
Drop created_at column from session_store.db

### PR DESCRIPTION
**Pull request by AntonyMilneQB**
## Description

`demo-project/data/session_store.db` contained a column `created_at` which was not doing anything (it contained only null values, and it's not referred to anywhere in the codebase). I think it must be a leftover from when Lim was playing around and made the data in the first place.

I've removed the column from the table just to be tidy and so no one has to try and figure out what it's for again in the future.

## Development notes

Ran the following SQL (only supported in recent version of SQLite):
```
ALTER TABLE runs DROP COLUMN created_at;
```

## QA notes

All experiment tracking data is still there and shown on the frontend as before.

## Checklist

- [ ] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro-viz/pull/781"></a>

### CODE REVIEW

**Review by MerelTheisenQB — APPROVED** [review]
👍

**Review by studioswong — APPROVED** [review]
Nice spot 👍 

On a side note, I assume this `created_at` field is a one-off thing / manually created field that's only found in the `session_store` db for `demo-project`, and not a field that's generated during the initial set up of the session store?

**Review by rashidakanchwala — APPROVED** [review]
Thanks Antony!

**Comment by AntonyMilneQB** [comment]
> 

Yes indeed - I checked by deleting the session_store.db and doing a `kedro run` to make a fresh new one, and the column isn't there.

**Review by tynandebold — APPROVED** [review]

**Comment by limdauto** [comment]
@AntonyMilneQB yes, thank you. It was indeed just used for the demo project session store. It's a by product of this spike: https://github.com/kedro-org/kedro-viz/pull/687

**Comment by AntonyMilneQB** [comment]
@limdauto cool, thanks for the explanation and the extra information on schema migration. 

We shouldn't need to record the timestamp any more, since it has now been decided that `run_id = session_id = timestamp` - see https://github.com/kedro-org/kedro-viz/issues/764. Please do take a look and see if you think this is not the right thing to do actually, it would be great if you could just check if we're missing something!

**Comment by limdauto** [comment]
@AntonyMilneQB oh that's great to know. Yea that should simplify things for sure.

**Pull request merged**
