### PR TITLE
Relax `semver` requirement bound, add back comment

### PR DESCRIPTION
**Pull request by deepyaman**
## Description

Related to https://github.com/kedro-org/kedro-plugins/issues/269

Don't want to break compatibility for people using `kedro-airflow` (or other libraries depending on older versions of `semver`) for no reason.

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro-viz/pull/1452"></a>

### CODE REVIEW

**Comment by astrojuanlu** [comment]
xref #1419 cc @rashidakanchwala

**Comment by deepyaman** [comment]
@astrojuanlu @rashidakanchwala @tynandebold bump on https://github.com/kedro-org/kedro-viz/pull/1447; should fix the Mypy issues (`unused-ignore`, no longer necessary due to fix in `kedro@main`).

**Review by rashidakanchwala — APPROVED** [review]

**Comment by sbrugman** [comment]
@deepyaman Thank you! Could we please do a patch release? 
This issue is currently blocking.

**Comment by tynandebold** [comment]
@sbrugman release PR is up now https://github.com/kedro-org/kedro-viz/pull/1458. Should be out soon.

**Comment by tynandebold** [comment]
@sbrugman the release is out.

**Pull request merged**
