### PR TITLE
Fix plots on metadata panel

### LINKED ISSUE #1022: Matplotlib and Plotly visualizations aren't displaying in Metadata panel
## Description

Matplotlib and Plotly visualizations aren't displaying in the Metadata panel.

I think this was introduced in #964 or #984. A remedy was tried in #1014, though the problem persists.

## Steps to Reproduce

1. Run Viz locally
2. Go to the experiment tracking page
3. Select a run that doesn't have any plots
4. Go to the flowchart page
5. Click on a node with a Matplotlib image Plotly visualization

## Expected Result

A visualization should display.

## Actual Result

No visualization displays. Here's the error for Matplotlib:

```
2022-08-19 08:03:34,768 - uvicorn.access - INFO - None:0 - "GET /api/nodes/af15a59c HTTP/1.1" 500
2022-08-19 08:03:34,768 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    raise exc from None
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 78, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 216, in app
    raw_response = await run_endpoint_function(
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/tynandebold/sites/kedro-viz/package/kedro_viz/api/rest/router.py", line 52, in get_single_node_metadata
    return DataNodeMetadata(node)
  File "<string>", line 3, in __init__
  File "/Users/tynandebold/sites/kedro-viz/package/kedro_viz/models/flowchart.py", line 592, in __post_init__
    self.image = dataset.load()
  File "/Users/tynandebold/sites/kedro/kedro/io/core.py", line 599, in load
    return super().load()
  File "/Users/tynandebold/sites/kedro/kedro/io/core.py", line 195, in load
    raise DataSetError(message) from exc
kedro.io.core.DataSetError: Failed while loading data from data set MatplotlibWriter(filepath=/Users/tynandebold/sites/kedro-viz/demo-project/data/08_reporting/matplot_lib_single_plot.png, protocol=file, save_args={}).
[Errno 21] Is a directory: '/Users/tynandebold/sites/kedro-viz/demo-project/data/08_reporting/matplot_lib_single_plot.png'
```

And the one for Plotly:

```
2022-08-19 08:17:04,990 - uvicorn.access - INFO - 127.0.0.1:54066 - "GET /api/nodes/c6992660 HTTP/1.1" 500
2022-08-19 08:17:04,990 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    raise exc from None
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 78, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 216, in app
    raw_response = await run_endpoint_function(
  File "/Users/tynandebold/opt/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/tynandebold/sites/kedro-viz/package/kedro_viz/api/rest/router.py", line 52, in get_single_node_metadata
    return DataNodeMetadata(node)
  File "<string>", line 3, in __init__
  File "/Users/tynandebold/sites/kedro-viz/package/kedro_viz/models/flowchart.py", line 590, in __post_init__
    self.plot = dataset.load()
  File "/Users/tynandebold/sites/kedro/kedro/io/core.py", line 599, in load
    return super().load()
  File "/Users/tynandebold/sites/kedro/kedro/io/core.py", line 195, in load
    raise DataSetError(message) from exc
kedro.io.core.DataSetError: Failed while loading data from data set JSONDataSet(filepath=/Users/tynandebold/sites/kedro-viz/demo-project/data/08_reporting/price_histogram.json, load_args={}, protocol=file, save_args={}).
[Errno 21] Is a directory: '/Users/tynandebold/sites/kedro-viz/demo-project/data/08_reporting/price_histogram.json'
```

## Checklist
- [x] Include labels so that we can categorise your issue

### PR DESCRIPTION
**Pull request by rashidakanchwala**
## Description

Resolves #1022 

## Development notes

Earlier we were setting  `self.dataset._version = None` if no dataset was found in experiment tracking. If you do that `self.dataset.load()` function on Kedro will return `None` when you try to call it from the flowchart. Hence it displayed the error 'is not a directory.'

So i changed this in two places to `self.dataset._version = Version(None, None)` so now `self.dataset.load()` will fetch the latest version.

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro-viz/pull/1023"></a>

### CODE REVIEW

**Review by tynandebold — APPROVED** [review]
Works well for me and fixes the problem as spelled out in the issue! Nice one.

Will let @AntonyMilneQB have the final say :)

**Comment by AntonyMilneQB** [comment]
🎉 Great work Rashida!

This is almost certainly the right fix but I'd like to understand a bit better exactly why it wasn't working before, because it means my understanding of how Kedro dataset loading works isn't currently correct, and maybe there's actually a kedro bug here 🤔 So let's have a chat!

**Comment by tynandebold** [comment]
@AntonyMilneQB is that conversation a blocker for merging this and then releasing a patch fix?

**Review by AntonyMilneQB — APPROVED** [review]
@tynandebold no, happy to approve now and understand fully later!

**Pull request merged**
