### PR TITLE
Release v.4.4.0

### PR DESCRIPTION
**Pull request by studioswong**
## Description

Release v4.4.0.

This release contains the export CSV, popup reminder, display props for React Component, as well as display improvements for the experiment tracking page. 

## Development notes

I've made a small update to the release notes, as well as bumped the version. 

## QA notes

N/A

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro-viz/pull/807"></a>

### CODE REVIEW

**Review by tynandebold — APPROVED** [review]
Looks good!

**Review by yetudada — APPROVED** [review]
Thank you! 🚀

**Review by rashidakanchwala — APPROVED** [review]
thanks @studioswong

**Review by MerelTheisenQB — APPROVED** [review]
LGTM! :shipit:

**Review by AntonyMilneQB — APPROVED** [review]

**Pull request merged**
