### PR TITLE
Handle Github pages 404 issue

### PR DESCRIPTION
**Pull request by jitu5**
## Description

Resolves https://github.com/kedro-org/kedro-viz/issues/2048

This pull request includes changes to fix a 404 error on the experiment tracking page, and to ensure the 404 page is correctly redirect to root and manage by React router internally by keeping the content of the index.html and 404.html same.

## Development notes

Redirect handling:

* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L16-R16): Modified the build script to copy `index.html` to `404.html` to ensure the 404 page is correctly served.

## QA notes

I have deployed the changes to Github pages https://jitu5.github.io to test.

## Checklist

- [X] Read the [contributing](/CONTRIBUTING.md) guidelines
- [X] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [x] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Watching this in slow motion was... interesting 😄 

kedro-viz-404

On the other hand, actual faulty URLs are handled in a strange way now:

image

Compare that with how it's handled locally:

image

I think this is smart but I fear it might have some unintended consequences...

**Comment by jitu5** [comment]
@astrojuanlu In slow motion you show that text "// in 404.html // in 404.html" was just for testing, I forgot to deploy the latest one , but now its updated. now it shows "Redirecting..."
Screenshot 2024-11-08 at 11 15 33 a m

**Comment by jitu5** [comment]
@astrojuanlu 

> On the other hand, actual faulty URLs are handled in a strange way now:

I fixed it now, if any sub path other than experiment-tracking is hit directly like this https://jitu5.github.io/experiment-trackingadsd, now it will be redirect to home/landing page.

**Comment by jitu5** [comment]
@astrojuanlu 

> Compare that with how it's handled locally:

This approach is specifically added for Github pages, on hitting faulty URLs it redirect you to our custom 404.html but locally thing works same as before.

**Review by rashidakanchwala — APPROVED** [review]
Look's great now! thanks @jitu5 .. this was a tough one to fix, and u did it in a minimal way!

**Review by tynandebold — COMMENTED** [review]
Did you try using the exact same contents of the `index.html` file for the `404.html`?

I just had to solve this issue for AlloyViz, which is also deployed to GH pages. 

[This](https://github.com/McK-Internal/verticalx-alloy-viz/blob/main/alloy_viz_fe/package.json#L9) is how I did it: 

```
"build": "tsc && vite build && cp ./dist/index.html ./dist/404.html",
```

Might not be the same. Wanted to share my findings in case they were helpful!

**Comment by jitu5** [comment]
> Did you try using the exact same contents of the `index.html` file for the `404.html`?
> 
> I just had to solve this issue for AlloyViz, which is also deployed to GH pages.
> 
> [This](https://github.com/McK-Internal/verticalx-alloy-viz/blob/main/alloy_viz_fe/package.json#L9) is how I did it:
> 
> ```
> "build": "tsc && vite build && cp ./dist/index.html ./dist/404.html",
> ```
> 
> Might not be the same. Wanted to share my findings in case they were helpful!

@tynandebold Thanks for sharing your finding.
But using same content for 404.html from index.html is redirecting to landing page or root but, how you retain the original url and its params entered by user and then redirect to the same using client-side React-router ?

**Review by Huongg — APPROVED** [review]
amazing, all looking good for me 👍 thank you @jitu5

**Review by tynandebold — APPROVED** [review]

**Pull request merged**
