### PR TITLE
[Chore] Remove unnecessary test

### PR DESCRIPTION
**Pull request by limdauto**
## Description

As @AntonyMilneQB this test does the exact same thing as `test_endpoint_main_no_session_store` so removing it.

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by AntonyMilneQB** [comment]
Thanks for checking this! But I think we should probably remove the other test, `test_endpoint_main_no_session_store`, since that is associated with the fixture `example_api_no_session_store` that only gets used once so could also be removed.

Do we have tests for the main endpoint when there _is_ a session store? The fact there's a test called `test_endpoint_main_no_session_store` makes me feel like there should be something akin to `test_endpoint_main_session_store` somewhere - or is the session store stuff already covered by another set of tests? 🤔

**Comment by limdauto** [comment]
@rashidakanchwala do you have any suggestion about cleaning up these tests? Otherwise I will do another pass and rejig things a bit.

**Review by rashidakanchwala — APPROVED** [review]
It makes sense... both tests do the same chk

**Review by rashidakanchwala — CHANGES_REQUESTED** [review]
hi @AntonyMilneQB  is right -- the fixture example_api_no_session_store is the same as example_api. So instead of removing test_endpoint_main.  we can remove the test_endpoint_main_no_session_store for now

in the Kedro-viz backlog, we still have a ticket (KED-2910) to write an integration test for session_store. 
Other sqlite_store unit tests are covered in test_intergration/sqlite folder. 
Also, in test_graphql/conftest -- we are mocking the db_sessions!

**Comment by limdauto** [comment]
@AntonyMilneQB @rashidakanchwala thanks. pushed

**Review by rashidakanchwala — APPROVED** [review]
Thanks Lim!!

**Pull request merged**
