### PR TITLE
Zoom is reset each time a node or dataset is selected

### PR DESCRIPTION
**Pull request by cvetankanechevska**
Signed-off-by: Cvetanka <cventanka_nechevska@external.mckinsey.com>

## Description

Fix: #882 

## Development notes

Not updating the view coordinates when the rightSidebar is open or closed.

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro-viz/pull/988"></a>

### CODE REVIEW

**Comment by comym** [comment]
Hi, here are my comments:

I like how the zoom in/out mechanism is now independent of the opening and closing from the metadata panel. It works perfectly.

However a detail we are missing is to make sure the selected node is always visible and centred to the reduced viewport. Sometimes you select a node and when the metadata panel opens, it goes over the top and you can't see your selected node anymore. Please check this gif where I show it happening:

Screen Recording 2022-07-28 at 10 27 20

In sum, the selected node should be always visible. For that, we don't need to play with zooming in or out, we just make sure we centre the selected node this way:

Screenshot 2022-07-28 at 10 28 47

And this is what I mean when I say "the reduced viewport" to the flowchart:

Screenshot 2022-07-28 at 10 36 56

Many thanks

**Review by tynandebold — CHANGES_REQUESTED** [review]
This is a great start. I agree with Gabriel's comments. We need to ensure we center the selected node.

I think you'll have more success by editing the code [here](https://github.com/kedro-org/kedro-viz/blob/5aebdfb43332b20334edcf5011bba4ce43886dd1/src/components/flowchart/flowchart.js#L389-L399) than by doing your `if` statement.

Just playing around with it a bit this morning I had some success with this:

```js
const transform = viewTransformToFit({
  offset,
  focus,
  viewWidth: chartWidth,
  viewHeight: chartHeight,
  objectWidth: graphWidth,
  objectHeight: graphHeight,
  minScaleX: 0.2,
  minScaleFocus: this.props.visibleMetaSidebar
    ? this.props.chartZoom.scale
    : 0.3,
  focusOffset: this.props.visibleMetaSidebar ? 0.01 : 0.8,
});
```

Another case we need to think about is what happens when you're zoomed in quite a bit and we open a modular pipeline. In that case, I think we need to zoom out a bit, since a lot of things are expanding. I have an idea how to do that. We can talk about it if you'd like.

**Comment by Huongg** [comment]
hey @cvetankanechevska I checked briefly, one thing I notice that the `this.props.visibleMetaSidebar` does not get updated when you close the panel directly. If you can trace it back to where this props gets updated, and why it's not updated when you click the close button directly, it might help to solve the issue. 
 What do you think?

**Review by tynandebold — APPROVED** [review]

**Review by Huongg — APPROVED** [review]
👍 LGTM

**Pull request merged**
