### PR TITLE
[KED-3046] Remove references to quantum black labs where appropriate

### PR DESCRIPTION
**Pull request by SajidAlamQB**
## Description

There's a few mentions that kedro is authored by QuantumBlack Labs (e.g. in kedro docs, setup.,py, `kedro info`). Following the migration to LF these shouldn't be there any more.

Best way to find them is just to search "quantumblack" in the codebase - there's not that many results to check through.

Additionally you will also have to update URLs for Kedro-Airflow, Kedro-Docker and Kedro-Telemetry as they have completely changed repo location.

As well as kedro repository, you should check kedro-community, kedro-plugins, kedro-viz and kedro-training. kedro-starters has already been updated.

https://jira.quantumblack.com/browse/KED-3046

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by SajidAlamQB** [comment]
There are quite a few references to `quantumblack/kedro-ui` which seems to rely on the [Kedro UI NPM repo ](https://www.npmjs.com/package/@quantumblack/kedro-ui). I've left them as is but I think we need to rename the repo.

**Review by limdauto — APPROVED** [review]
Thank you. Re the kedro-ui reference, no let's not rename for now. We are bringing them inside this repo.

**Review by MerelTheisenQB — APPROVED** [review]
👍

**Review by tynandebold — COMMENTED** [review]
There's a QB email address here: https://github.com/kedro-org/kedro-viz/blob/main/CODE_OF_CONDUCT.md#enforcement

We might need to change that, too?

**Pull request merged**
