### PR TITLE
Add markdown support for version reminders

### PR DESCRIPTION
**Pull request by SajidAlamQB**
## Description

Related to: https://github.com/kedro-org/kedro-viz/issues/1786

The reminder pop-up notification doesn't parse markdown ` backticks this PR will attempt to add support for it using [markdown-it](https://www.npmjs.com/package/markdown-it).

## Development notes
image

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [x] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by rashidakanchwala — COMMENTED** [review]
I was considering that, given the simplicity of our markdown needs—primarily replacing backticks with code-blocks —we could directly use < code > tags for any backticks we encounter. This approach would eliminate the need for any additional dependencies. What do you think?

**Comment by SajidAlamQB** [comment]
> I was considering that, given the simplicity of our markdown needs—primarily replacing backticks with code-blocks —we could directly use < code > tags for any backticks we encounter. This approach would eliminate the need for any additional dependencies. What do you think?

That makes sense, I thought we wanted to support more markdown overall, happy to go with that instead.

**Comment by jitu5** [comment]
@SajidAlamQB If we are not planing to add more style to `<code>` block then everything else looks good to me.

**Review by jitu5 — APPROVED** [review]
LGTM!

**Pull request merged**
