### PR TITLE
Release v4.5.0

### PR DESCRIPTION
**Pull request by tynandebold**
## Description

Release v4.5.0.

It's a minor-version release since it’s more than just small bug fixes.

Here's what's going in:

#### Major features and improvements

- Added support for Python 3.9 and 3.10. (#815)

#### Bug fixes and other changes

- Change route name from `runsList` to `experiment-tracking`. (#820)
- Update feature flag description to remind the user of the need for page refresh to apply settings. (#821)
- Fix experiment tracking not showing run details bug on Windows. (#809)
- Fix rendering of React component instance with custom routes. (#838)
- Improve performance when many datasets are missing. (#832)
- Fix flowchart not showing on initial load for static data inputs. (#843)

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [x] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro-viz/pull/844"></a>

### CODE REVIEW

**Review by AntonyMilneQB — APPROVED** [review]
Just a quick check: "Change route name from runsList to experiment-tracking. (https://github.com/kedro-org/kedro-viz/pull/820)" isn't a breaking change is it?

**Comment by tynandebold** [comment]
> Just a quick check: "Change route name from runsList to experiment-tracking. (#820)" isn't a breaking change is it?

This is a tricky one. I would say no, it isn't. But if someone is using `/runslist` programmatically for something then yes, it will break whatever they're doing. Given our tepid adoption at the moment, I don't think this is a big risk right now, thankfully.

**Review by MerelTheisenQB — APPROVED** [review]
:shipit: Lots of great fixes and improvements in this release! 💥

**Comment by studioswong** [comment]
I thought we are aiming to also incorporate #843 and #838 before we release?

**Review by studioswong — APPROVED** [review]

**Review by rashidakanchwala — APPROVED** [review]

**Pull request merged**
