### PR TITLE
Fix posix path conversion on Windows in DatasetStatsHook

### LINKED ISSUE #1797: Warning when parsing filepath in pandas.SQLQueryDataset even though pipeline works fine.
## Description

https://kedro-org.slack.com/archives/C03RKP2LW64/p1709912797979079

## Context
How has this bug affected you? What were you trying to accomplish?

The impact is relatively minor. I just see a warning.

## Steps to Reproduce

1. Put a SQL script into an accessible path.
2. Put a SQL query dataset in the catalog with a filepath assigned to the path of the SQL script.
3. Run kedro.

## Expected Result

I expect that a warning should not be raised if nothing is wrong or situationally risky.

## Actual Result

I get a warning even though the pipeline works as desired. Purportedly this might be a Kedro-viz issue.

See [here](https://kedro-org.slack.com/archives/C03RKP2LW64/p1709912797979079).

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version: N/A
* Operating system and version: Windows 10
* NodeJS version used (if relevant): N/A
* Kedro version used (if relevant): See [here](https://kedro-org.slack.com/archives/C03RKP2LW64/p1709915286914139?thread_ts=1709912797.979079&cid=C03RKP2LW64).
* Python version used (if relevant): 3.10

### PR DESCRIPTION
**Pull request by ravi-kumar-pilla**
## Description

Resolves #1797 

## Development notes

* Passing PurePath to the get_filepath_str function instead of str filepath which complains on Windows
* Addressed warnings of deprecation in demo-project

```python
file_path = get_filepath_str(Path(dataset._filepath), dataset._protocol)
```

## QA notes

* All tests should pass
* When running on a windows machine, there should not be any warning message as shown [here](https://kedro-org.slack.com/archives/C03RKP2LW64/p1709912797979079) -

```bash
WARNING  Unable to get file size for the dataset SQLQueryDataset(execution_options={}, filepath=C:/path/to/data/00_scripts/dim_postal_code.sql, load_args={}, sql=None): 'str' object has no attribute 'as_posix'
```
## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [x] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by astrojuanlu — COMMENTED** [review]
Declining review requests of small engineering PRs for my own sanity 🙏🏽 If you need extra reviews kindly ask the framework team.

**Comment by ravi-kumar-pilla** [comment]
> Declining review requests of small engineering PRs for my own sanity 🙏🏽 If you need extra reviews kindly ask the framework team.

Sure, I added as you were present in the initial discussion. But, I will make sure you are not included on small engineering PRs. Thank you 👍

**Review by SajidAlamQB — APPROVED** [review]
Looks good to me, thanks for fixing this!

**Review by rashidakanchwala — APPROVED** [review]
LGTM. Thanks :)

**Pull request merged**
