### PR TITLE
telemetry/add kedro_Viz_version to heaps

### PR DESCRIPTION
**Pull request by Huongg**
## Description

Fixes https://github.com/kedro-org/kedro-plugins/issues/923

To include kedro_viz_version when user interacts with viz

## Development notes

When test this locally, ensure you enable `consent: true` in `project-demo telemetry`, and in the heap dash board development environment, it should show kedro_viz_version as one of the property
Screenshot 2024-11-15 at 13 17 39

## Checklist

- [ ] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by rashidakanchwala** [comment]
i cannot checkout this branch @jitu5 , can you ??

**Comment by jitu5** [comment]
> i cannot checkout this branch @jitu5 , can you ??

@rashidakanchwala Yes I can.

**Comment by jitu5** [comment]
Hey @Huongg 

I tested locally and here as well https://heapanalytics.com/app/env/2388822444/data-galaxy?view=live-data-feed
but I cant see kedro-viz version on heap data for both CLI and UI event
Screenshot 2024-11-18 at 1 01 29 p m Screenshot 2024-11-18 at 1 01 18 p m

**Comment by rashidakanchwala** [comment]
@jitu5 , u r on prod environment, u should check dev environment

**Comment by Huongg** [comment]
hey @jitu5 let me know if you can see it in the development environment. Im happy to jump on the call to test this together. This is what I currently see from my side

Screenshot 2024-11-18 at 13 25 48

**Review by jitu5 — APPROVED** [review]
Thanks @Huongg

**Review by rashidakanchwala — APPROVED** [review]
i have had some difficulties checking out this branch. but since Jitendra tested and approved. I will approve as well as code wise it looks fine.

**Review by rashidakanchwala — CHANGES_REQUESTED** [review]
Yup. tried it . not working for me as well

**Comment by Huongg** [comment]
hey both I just pushed the change and tested again and its working from my side. Just tested with @rashidakanchwala too, can you confirm its okay now?

**Review by rashidakanchwala — APPROVED** [review]
thanks Huong!

**Review by jitu5 — APPROVED** [review]

**Pull request merged**
