### PR TITLE
Disable uvicorn logger to remove duplicated messages

### PR DESCRIPTION
**Pull request by AntonyMilneQB**
## Description
Did you ever notice how chatty kedro-viz logging is and that all the messages are duplicated? 
image

Now that we're changing kedro's default logger to something more beautiful in https://github.com/kedro-org/kedro/issues/1512, the duplication is even more stark and makes the output look wack:
image

The reason for this is that `uvicorn` sets up its own custom logger, and then kedro's logging is also there, so messages get duplicated. The solution is to disable `uvicorn`'s logger. I left the log level set to what they use (INFO) so that we still get a lot of messages, just they're no longer duplicated.

After https://github.com/kedro-org/kedro/issues/1512 and this are merged, kedro viz log messages will then look super sexy, like this:
image

There's no need to wait until #1512 is merged to merge this though. We can go ahead with this right away.

## Checklist

- [ ] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro-viz/pull/870"></a>

### CODE REVIEW

**Comment by datajoely** [comment]
🔥

**Review by limdauto — APPROVED** [review]
Danker. I'm guilty of never reading this log

**Comment by limdauto** [comment]
@AntonyMilneQB although could you help me check if you throw an error in one of the endpoint, does the stack trace get logged correctly?

**Review by tynandebold — APPROVED** [review]
Excellent

**Pull request merged**
