### PR TITLE
Fix/disconnected graph with nested modular pipelines

### PR DESCRIPTION
**Pull request by jmholzer**
## Description

This PR resolves [#1036](https://github.com/kedro-org/kedro-viz/issues/1036). A minimally-invasive change to the code now causes nested modular pipelines to render correctly.

## Development notes

I replicated the project in which the error was first seen ([#1036](https://github.com/kedro-org/kedro-viz/issues/1036)). I was able to reproduce the error seen by the user reporting the bug:

Screenshot 2022-10-05 at 11 43 52

After making my changes, the project renders correctly in Viz:

Screenshot 2022-10-05 at 11 52 22

I have additionally (manually) tested the following projects, all of which also render correctly:
- Viz Demo Project
- Spaceflights
- Iris

After the current fix, there is still a problem in rendering where one of the datasets is initially rendered outside of the modular pipeline to which it belongs. After expanding and closing the pipeline, this error in rendering is no longer present. I have discussed this with @tynandebold. It is not clear whether this is a problem with the backend tree-generation code or with the rendering code on the frontend. I will open a separate issue to investigate this further.

A big problem in the investigation of this ticket was the backend code, which in my view has a few problems and is potentially a source of further, unreported bugs (e.g. the rendering issue discussed above). I will open a separate ticket concerning a refactor of this.

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro-viz/pull/1119"></a>

### CODE REVIEW

**Comment by limdauto** [comment]
Thanks for the fix and for looking into refactoring the modular pipeline tree generation code. If you need any context in how/why something was done in a certain way I would love to be able to help.

**Comment by jmholzer** [comment]
> Thanks for the fix and for looking into refactoring the modular pipeline tree generation code. If you need any context in how/why something was done in a certain way I would love to be able to help.

Thanks so much @limdauto, really appreciate it!

**Review by rashidakanchwala — APPROVED** [review]
Look's good to me. definitely solves the problem of disconnected graphs. 

i tested it and the thing I noticed is the sidebar now has two sub_pipeline.preprocesed data and on the first load you do a see a disconnected sub_pipeline.preprocessed data node which disappears when you expand and collapse. So definitely there's an issue with the namespacing that needs to be tackled as a part of another refactor ticket. 

see images below on what I mean 

Screenshot 2022-10-06 at 12 08 49

Screenshot 2022-10-06 at 12 08 59

**Review by tynandebold — APPROVED** [review]
Looks great. Thank you for this!

**Review by noklam — APPROVED** [review]
Thanks for the fix! I am not gonna block this PR since I don't know too much about the viz.

Is there any test for the generated tree structure? I guess we will need some tests for this before we start any refactoring work.

**Pull request merged**
