### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jmnunezd**
changing a broken hyperlink on the main README.md with one that's actually available
Screenshot 2023-06-21 at 4 50 00 PM

## Description

The Old link <https://docs.kedro.org/en/stable/logging/experiment_tracking.html> doesn't work anymore

## Development notes

I'm chaging the old link:
https://docs.kedro.org/en/stable/logging/experiment_tracking.html
with this one:
https://docs.kedro.org/en/stable/experiment_tracking/index.html

## QA notes

This doesn't change any source code, just the main readme.md

## Checklist

- [X] Read the [contributing](/CONTRIBUTING.md) guidelines
- [N/A] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [N/A] Updated the documentation to reflect the code changes
- [N/A] Added new entries to the `RELEASE.md` file
- [N/A] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro-viz/pull/1409"></a>

### CODE REVIEW

**Review by stichbury — APPROVED** [review]
Wow that's really old, thank you for fixing it. I'll sort out the redirect and also review the rest of the page to make sure we haven't missed any others.

**Comment by stichbury** [comment]
@rashidakanchwala Please don't merge this yet -- I'm working on the branch to check other links etc.

**Review by tynandebold — APPROVED** [review]

**Comment by stichbury** [comment]
@tynandebold @rashidakanchwala Can I just check something please?

Does this still apply?

  To install the standalone React component:
  ```bash
  npm install @quantumblack/kedro-viz
  ```

That is, is it still published at @quantumblack or has that changed now we're in LF AI&Data?

**Comment by tynandebold** [comment]
That's still correct. It's namespaced to QB even though it's open sourced.

**Comment by jmnunezd** [comment]
What else do we need in order to merge this?

**Comment by tynandebold** [comment]
It's merged now, @jmnunezd. Thank you for the fix!

**Pull request merged**
