### PR TITLE
Add UnavailableDataset as a default dataset for lite mode

### PR DESCRIPTION
**Pull request by ravi-kumar-pilla**
## Description

Related to #2058 

## Development notes

* Created a custom dataset `UnavailableDataset`
* Updated the default dataset from `MemoryDataset` to `UnavailableDataset` in `--lite` mode.
* Updated filepath to have an empty string as `N/A` instead of `-` as suggested by @stephkaiser 
* Updated tests

## QA notes

* When you run `kedro viz --lite` with `kedro-datasets` missing in the conda env, the metadata panel for the dataset should show the dataset type as `UnavailableDataset` if the dataset is mentioned in catalog.py (i.e., not a MemoryDataset)

Screenshot 2024-09-05 at 2 43 30 PM

* All tests should pass

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [x] Added new entries to the `RELEASE.md` file
- [x] Added tests to cover my changes

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Thanks @ravi-kumar-pilla - could you clarify what was the situation before this PR?

**Comment by ravi-kumar-pilla** [comment]
> Thanks @ravi-kumar-pilla - could you clarify what was the situation before this PR?

Hi @astrojuanlu , Thanks for reviewing. Before this change, the default was `MemoryDataset` . This PR is part of making users aware of the missing dependency. `MemoryDataset` will be a bit misleading as the dataset is registered in the catalog.

**Comment by stephkaiser** [comment]
thanks Ravi! using Gitpod, filepath is showing as N/A for me 👍 but still shows MemoryDataset, maybe i did something wrong? 

Screenshot 2024-09-10 at 12 14 13
Screenshot 2024-09-10 at 12 13 15

**Comment by ravi-kumar-pilla** [comment]
> thanks Ravi! using Gitpod, filepath is showing as N/A for me 👍 but still shows MemoryDataset, maybe i did something wrong?
> 
> Screenshot 2024-09-10 at 12 14 13 Screenshot 2024-09-10 at 12 13 15

Thanks for reviewing. Yes these are actually MemoryDatasets (as they are not registered in the DataCatalog). We will show `UnavailableDataset` to the datasets which are registered in the DataCatalog but the dependency is not installed. 

For example, `companies` is registered in DataCatalog as below but has a missing dependency of `pandas.CSVDataset`, so companies metadata will have dataset type as `UnavailableDataset`. I hope this is clear. Thank you

```yaml
companies:
  type: pandas.CSVDataset
  filepath: ${_base_location}/01_raw/companies.csv
  metadata:
    kedro-viz:
      layer: raw
      preview_args:
        nrows: 5
```

**Review by rashidakanchwala — APPROVED** [review]
LGTM. thanks! <3

**Pull request merged**
