### PR TITLE
Fix packaging

### LINKED ISSUE #1267: PyPI sdists are not self-contained
## Description
As per title. The reason is that `package.json` and `README.md` are not included in the sdist.

## Context
I was trying to add kedro-viz to conda-forge, picking up on https://github.com/conda-forge/staged-recipes/pull/21441.

## Steps to Reproduce

```
$ pip install "kedro-viz==5.3.0" --no-binary :all:
Collecting kedro-viz==5.3.0
  Downloading kedro-viz-5.3.0.tar.gz (5.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 81.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-w73ekeu9/kedro-viz_74c1ed35d82c47aa8afa50b9d1762ce6/setup.py", line 20, in <module>
          with open(path.join(here, path.pardir, "package.json")) as data:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-w73ekeu9/kedro-viz_74c1ed35d82c47aa8afa50b9d1762ce6/../package.json'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
You should consider upgrading via the '/tmp/kedro-viz-5.3.0/.venv/bin/python3 -m pip install --upgrade pip' command.
```

## Expected Result
Installing from a PyPI sdist should work.

## Actual Result
Trying to install from a PyPI sdist gave an immediate error.

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Operating system and version: macOS Ventura and Linux

## Checklist
- [x] Include labels so that we can categorise your issue

### LINKED ISSUE #1527: Move to pyproject.toml
## Description

Kedro-viz currently has `requirements.txt` file which the users use to install all the requirements. We want to now move to pyproject.toml which is a newer way of dependency management.

Pyproject.toml has some advance features that will also make our depandabot much more .... smarter? ;) 

## Checklist

- [x] Include labels so that we can categorise your feature request

### PR DESCRIPTION
**Pull request by astrojuanlu**
## Description

Make sdists self-contained, hence fix #1267

## Development notes

Commits:

1. cf738296 Remove direct invokations of `setup.py`, which have been deprecated for about 2 years https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
2. 44538613 Migrate to `pyproject.toml` using @MehdiNV work in #1584 as baseline with some updates, hence fix #1527
3. 495a54b1 Migrate from `setuptools` to `hatchling` https://hatch.pypa.io/, same backend vizro uses (cc @antonymilne), as a preparation to eventually address #1611 and also fix #1267
4. e22a6ba0 Move `README.md` to `package/` and create root symlink to retain GitHub preview

## QA notes

1. Run `make package` in `main` and with this PR, save the resulting sdist and wheel in `dist.old` and `dist` respectively
2. Unzip the resulting `.tar.gz`, and compare the `PKG-INFO` files of both sdists - there should be only lines out of order and other non consequential changes directories with `main` and with this PR.
3. Compare the `tree` structure of both sdists - only metadata files should have changed.

```diff
--- old.tree	2024-02-27 00:41:59
+++ new.tree	2024-02-27 00:42:29
@@ -1,5 +1,6 @@
-dist.old/kedro-viz-7.1.0/
+dist/kedro_viz-7.1.0/
 ├── PKG-INFO
+├── README.md
 ├── kedro_viz
 │   ├── __init__.py
 │   ├── api
@@ -81,10 +82,7 @@
 │       ├── __init__.py
 │       ├── layers.py
 │       └── modular_pipelines.py
-├── setup.cfg
-├── setup.py
-└── tests
-    ├── test_import.py
-    └── test_server.py
+├── pyproject.toml
+└── requirements.txt
 
-19 directories, 69 files
+18 directories, 68 files
```

4. Unzip both wheel files and compare the `*.dist-info` directories - there should be only lines out of order but the number of files in `RECORD` should be basically the same.

```diff
...
diff --color=auto -u dist.old/kedro_viz-7.1.0.dist-info/RECORD dist/kedro_viz-7.1.0.dist-info/RECORD
--- dist.old/kedro_viz-7.1.0.dist-info/RECORD   2024-02-26 23:37:50
+++ dist/kedro_viz-7.1.0.dist-info/RECORD       2020-02-02 00:00:00
@@ -62,8 +62,7 @@
 kedro_viz/services/__init__.py,sha256=-ZfXYz5XecClJZK-cjZsoRrCpQCThwc3TXvCyDs0Sek,186
 kedro_viz/services/layers.py,sha256=_JO8mbmA0ZzAMN2dcXVaDX89Gr_QtJDWtmDnUeX49gc,5263
 kedro_viz/services/modular_pipelines.py,sha256=Tx3ekpwjt981jmljezxgWlOVaWdxgVADKCY1QyIUC4Q,4064
-kedro_viz-7.1.0.dist-info/METADATA,sha256=j_RijhLdEdn3vEgHlpCUDyCGHq6u4Ho8zkVJ9VT_xwE,11619
-kedro_viz-7.1.0.dist-info/WHEEL,sha256=oiQVh_5PnQM0E3gPdiz09WCNmwiHDMaGer_elqB3coM,92
+kedro_viz-7.1.0.dist-info/METADATA,sha256=tkqndzIrnu7hy0Pnj760FEOCApMYIBI9n0e2gxoo6vg,11759
+kedro_viz-7.1.0.dist-info/WHEEL,sha256=TJPnKdtrSue7xZ_AVGkp9YXcvDrobsjBds1du3Nx6dc,87
 kedro_viz-7.1.0.dist-info/entry_points.txt,sha256=yCRpAmWDqux5fspKHZ03tRjHkmIjs8ypb1m3XuvWNMI,228
-kedro_viz-7.1.0.dist-info/top_level.txt,sha256=gWY-UrKtMq-3SUTv5Zww2hc6_ldAln47aYqCihTOyew,10
 kedro_viz-7.1.0.dist-info/RECORD,,
```

6. Verify that `pip install ./dist.old/...tar.gz` doesn't work (hence #1267) and `pip install ./dist/...tar.gz` fixes the issue
7. Launch `kedro viz run` on a test project after installing the new sdist, verify that everything works as expected (the HTML files are included)

## Checklist

- [ ] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by astrojuanlu** [comment]
```
package/kedro_viz/data_access/repositories/graph.py:46:8: R1737: Use 'yield from' directly instead of yielding each element one by one (use-yield-from)
```

linting failures unrelated

**Comment by astrojuanlu** [comment]
The `README.md` hack didn't get me very far though, now the e2e tests are failing. Exhausted a couple of avenues with Hatch and gave up for the day, asked a upstream https://github.com/pypa/hatch/discussions/1286

**Comment by rashidakanchwala** [comment]
This is amazing!!!!  -- thanks @astrojuanlu ! liking the nerd-snipe you.

**Comment by antonymilne** [comment]
Amazing PR! This is a HUGE improvement. 

Just two things I'm curious about:
1. What is the motivation for "https://github.com/kedro-org/kedro-viz/commit/e22a6ba0df118d2941ec26770cc1f8d59704db68 Move README.md to package/ and create root symlink to retain GitHub preview"?
2. What further steps would be needed to make `pip install git+...` on kedro-viz work?

**Comment by astrojuanlu** [comment]
1. `setup.py` had a `open("../README.md")`, that's not possible with static `pyproject.toml` (neither with setuptools nor with hatchling). I asked upstream https://github.com/pypa/hatch/discussions/1286 so far no response
2. That's the topic of https://github.com/kedro-org/kedro-viz/issues/1611 and will require a custom hook that builds the assets upon installation, but that's for a separate PR 🙃

**Review by ravi-kumar-pilla — APPROVED** [review]
This already looks great and I tried to resolve conflicts with main and fixed few issues. As per my understanding, this PR resolves -
1. https://github.com/kedro-org/kedro-viz/issues/1267
2. https://github.com/kedro-org/kedro-viz/pull/1584

There needs to be some work to resolve - https://github.com/kedro-org/kedro-viz/issues/1611

Thank you for the PR @astrojuanlu . I followed the QA notes and it works as expected.

**Review by astrojuanlu — COMMENTED** [review]
This looks good to me 👍🏼 Beware of the moving README.md as it will conflict with #1745 

If folks still want an explanation of some of the concepts, I'll be happy to give an overview. The fun part comes when trying to solve https://github.com/kedro-org/kedro-viz/issues/1611, this was just the beginning 😏

**Comment by ravi-kumar-pilla** [comment]
> This looks good to me 👍🏼 Beware of the moving README.md as it will conflict with #1745
@jitu5 fyi

**Review by rashidakanchwala — APPROVED** [review]
LGTM.

**Pull request merged**
